MusicLibraryWebApp/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace MusicLibraryWebApp.Models {
    public class Album {
        public string sid { get; set; }
        public int ano { get; set; }
        public string title { get; set; }
        public DateTime date { get; set; }
        public string coverPath { get; set; }
        public HttpPostedFileBase coverFile { get; set; }
    }
}

MusicLibraryWebApp/Models/DBAccess.cs
using System;
using System.Data;
using System.Data.SqlClient;

namespace MusicLibraryWebApp.Models {
    public class DBAccess {
        private static String ConnectionString = "Data Source=CYBER;User ID=sa;Password=123; Initial Catalog=MusicDB;Integrated Security=True";
        public SqlConnection conn = new SqlConnection(ConnectionString);
        public SqlCommand cmd;
        public SqlDataReader sdr;


        public void ConOpen() {
            if (conn.State == ConnectionState.Closed)
                conn.Open();
        }

        public void ConClose() {
            if (conn.State == ConnectionState.Open)
                conn.Close();
        }

        public void IUD(string query) {
            cmd = new SqlCommand(query, conn);
            cmd.ExecuteNonQuery();
        }



        //public 
        public SqlDataReader GetData(string query) {
            cmd = new SqlCommand(query, conn);
            sdr = cmd.ExecuteReader();
            return sdr;
        }



    }
}

MusicLibraryWebApp/Models/Singer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicLibraryWebApp.Models {
    public class Singer {
         public string Sid { get; set; }
         public string Sname { get; set; }
         public string Country { get; set; }
         public string Gender { get; set; }
         public string Email { get; set; }
         public string Password { get; set; }

    }
}

MusicLibraryWebApp/Models/Song.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;

namespace MusicLibraryWebApp.Models {
    public class Song {
        public string Sid { get; set;}
        public int Ano { get; set;}
        public int Sno { get; set; }
        public string Stitle { get; set; }  
        public string FilePath { get; set; }
        public HttpPostedFileBase Mp3File { get; set; }
    }
}

MusicLibraryWebApp/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using MusicLibraryWebApp.Models;
using System.Web.UI.WebControls;
using System.Data.SqlClient;

namespace MusicLibraryWebApp.Controllers {
    public class AlbumController : Controller {
        DBAccess obj = new DBAccess();
        [HttpGet]
        public ActionResult AddAlbum() {
            if (Session["sid"] != null)
                return View();
            return RedirectToAction("login", "Singer");
        }
        [HttpPost]
        public ActionResult AddAlbum(Album album) {
            string newFileName = $"{Session["Sid"]}_{album.ano}.jpg";
            //string fn = album.coverFile.FileName;
            string path = Server.MapPath(Path.Combine("~/Images/", newFileName));
            album.coverPath = "/Images/" + newFileName;
            album.coverFile.SaveAs(path);

            string q = $"INSERT INTO ALBUM VALUES('{Session["Sid"]}', '{album.ano}', '{album.title}', '{album.date}', '{album.coverPath}')";
            obj.ConOpen();
            obj.IUD(q);
            obj.ConClose();

            return View(album);
        }

        [HttpGet]
        public ActionResult ShowAlbums(string sid) {
            string q = $"SELECT ano, coverpath, title FROM Album WHERE sid = '{sid}'";
            obj.ConOpen();
            SqlDataReader sdr = obj.GetData(q);
            List<Album> albumlist = new List<Album>();
            while (sdr.Read())
                albumlist.Add(new Album { ano = int.Parse(sdr["ano"].ToString()), coverPath = sdr["coverpath"].ToString(), title = sdr["title"].ToString() });

            sdr.Close();
            obj.ConClose();

            return View(albumlist);
        }

    }
}

MusicLibraryWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicLibraryWebApp.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MusicLibraryWebApp/Controllers/SingerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using MusicLibraryWebApp.Models;

namespace MusicLibraryWebApp.Controllers {
    public class SingerController : Controller {

        DBAccess db = new DBAccess();
        // GET: Singer
        public ActionResult SignUpSinger() {
            return View();
        }

        [HttpPost]
        public ActionResult SignUpSinger(Singer s) {
            s.Sid = s.Email.Split('@')[0];
            db.ConOpen();
            string query = $"INSERT INTO Singer VALUES('{s.Sid}', '{s.Sname}', '{s.Country}', '{s.Gender}', '{s.Email}', '{s.Password}')";
            db.IUD(query);
            db.ConClose();  
            return View(s);
        }

        [HttpGet]
        public ActionResult login() {
            return View();
        }

        [HttpPost]
        public ActionResult login(Singer s) {
            db.ConOpen();
            db.cmd = new SqlCommand($"SELECT sid, sname FROM Singer WHERE sid = '{s.Sid}' AND password = '{s.Password}'", db.conn);
            SqlDataReader sdr  = db.cmd.ExecuteReader();
            sdr.Read();
            if (sdr.HasRows) {
                Session["Sid"] = sdr["sid"].ToString();
                Session["Sname"] = sdr["sname"].ToString();
            }
            else {
                Response.Write("<script>alert('Invalid User');</script>");
            }
            sdr.Close();
            db.ConClose();
            
            return RedirectToAction("DashBoard");
        }

        [HttpGet]
        public ActionResult DashBoard() {
            if (Session["sid"] != null) 
                return View();
            
            return RedirectToAction("login");
        }

        [HttpGet]
        public ActionResult logout() {
            Session.RemoveAll();
            return RedirectToAction("login");
        }
    }
}

MusicLibraryWebApp/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Reflection.Emit;
using System.Web;
using System.Web.Mvc;
using MusicLibraryWebApp.Models;

namespace MusicLibraryWebApp.Controllers {
	public class SongController : Controller {
		// GET: Song

		DBAccess obj = new DBAccess();
		public ActionResult ViewSongs(string sid, int ano) {
			string q = $"SELECT sno, stitle, filepath FROM Song WHERE sid = '{sid}' AND ano = '{ano}';";
			obj.ConOpen();
			SqlDataReader sdr = obj.GetData(q);
			List<Song> list = new List<Song>();
			while (sdr.Read())
				list.Add(new Song { Sno = int.Parse(sdr["sno"].ToString()), Stitle = sdr["stitle"].ToString(), FilePath = sdr["filepath"].ToString() });
			sdr.Close();
			obj.ConClose();
			return View(list);
		}
		[HttpGet]
		public ActionResult AddSong() {
			Song s = new Song() { Ano = int.Parse(Request.QueryString["ano"]) };
			return View(s);
		}

		[HttpPost]
		public ActionResult AddSong(Song s) {
			string filename = s.Mp3File.FileName;
			string ext = Path.GetExtension(filename);
			List<string> extensions = new List<string> { ".mp3", ".wav", ".m4a" };
			if (extensions.Contains(ext)) {
				string path = Server.MapPath(Path.Combine("~/Songs", $"{s.Stitle}{ext}"));
				s.Mp3File.SaveAs(path);
				s.FilePath = $"/Songs/{s.Stitle}{ext}";
				obj.ConOpen();
				string q = $"INSERT INTO Song VALUES('{Session["sid"]}', " +
					$"'{s.Ano}', '{s.Sno}', '{s.Stitle}', '{s.FilePath}')";
				obj.IUD(q);
				obj.ConClose();
			}

			return View();
		}


		[HttpGet]
		public FileResult DownloadSong(string filePath) {
			string path = Server.MapPath("~") + filePath;
			byte[] bytes = System.IO.File.ReadAllBytes(path);
			return File(bytes, "application/octet-stream", filePath);
		}

	}
}

MusicLibraryWebApp/Views/Album/AddAlbum.cshtml
@model MusicLibraryWebApp.Models.Album

@{
    ViewBag.Title = "Album";
}


@using (Html.BeginForm("AddAlbum", "Album", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    <b>Singer: @Session["Sid"]</b>
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        <table class="table">
@*            <tr>
                <td>
                    @Html.LabelFor(model => model.sid, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.sid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.sid, "", new { @class = "text-danger" })
                </td>
            </tr>*@

            <tr>
                <td>
                    @Html.LabelFor(model => model.ano, htmlAttributes: new { @class = "control-label col-md-2" })

                </td>
                <td>
                    @Html.EditorFor(model => model.ano, new { htmlAttributes = new { @class = "form-control" } })

                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })

                </td>
                <td>
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })

                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.date, new { htmlAttributes = new { type = "date", @class = "form-control" } })
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.coverFile, htmlAttributes: new { @class = "control-label col-md-2" })

                </td>
                <td>
                    @Html.TextBoxFor(model => model.coverFile, new { Type = "file", htmlAttributes = new { @class = "form-control" } })

                </td>
            </tr>
        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@if (IsPost) {
    <img src=@Model.coverPath height="300" width="300" />


}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicLibraryWebApp/Views/Album/ShowAlbums.cshtml
@model List<MusicLibraryWebApp.Models.Album>
@{
    ViewBag.Title = "ShowAlbums";
}

<h2>ShowAlbums</h2>
<b>SID: @Session["sid"]</b>
<div class="row">

    @foreach (var album in Model) {
        <div class="col-lg-4 mb-3 text-center py-3">
            @*            <a href=/Song/ViewSongs?sid =@Session["sid"] &&ano=@album.ano>*@
            <a href=@Url.Action("ViewSongs", "Song", new {sid = Session["sid"], ano = album.ano, title = album.title } )>

                <img class="rounded rounded-2" src=@album.coverPath height="200" width="200" />
            </a>
            <div>
                <b>Ano: </b>@album.ano <br />
                <b>Title: </b>@album.title
            </div>
        </div>
    }

</div>

MusicLibraryWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

MusicLibraryWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

MusicLibraryWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

MusicLibraryWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body data-bs-theme="dark">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Sign up", "SignUpSinger", "Singer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Login", "Login", "Singer", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MusicLibraryWebApp/Views/Singer/DashBoard.cshtml
@{
    ViewBag.Title = "DashBoard";
}

<h2>DashBoard</h2>
@Html.ActionLink("Logout", "logout", "Singer", new { area = "" }, new { @class = "nav-link" })

<b>SID: @Session["sid"]</b>
<br />
<b>Name: @Session["sname"]</b>


<h2>Singer Dashboard</h2>

<div class="d-flex justify-content-center gap-3">
    <div class="bg-black p-3 rounded rounded-3">
        @Html.ActionLink("Albums", "AddAlbum", "Album")
    </div>
    <div class="bg-black p-3 rounded rounded-3">
        @*        @Html.ActionLink("Show Albums", "ShowAlbums", "Album", new { id = Session["sid"] }, null)
        *@
        <a href=/Album/ShowAlbums?sid=@Session["sid"]>Show Albums</a>

    </div>
    <div class="bg-black p-3 rounded rounded-3">
        @Html.ActionLink("Songs", "songs", "Song")
    </div>
</div>

MusicLibraryWebApp/Views/Singer/SignUpSinger.cshtml
@model MusicLibraryWebApp.Models.Singer

@{
    ViewBag.Title = "Singup";
    List<SelectListItem> countries = new List<SelectListItem> {
        new SelectListItem { Text = "Pakistan", Value = "Pakistan" },
        new SelectListItem { Text = "India", Value = "India" },
        new SelectListItem { Text = "USA", Value = "USA" },
        new SelectListItem { Text = "UK", Value = "UK" },
    };
}

<h2>SignUpSinger</h2>

@using (Html.BeginForm()) {
    <div class="form-horizontal">
        <h4>Singer</h4>
        @Html.ActionLink("Login", "login", "Singer")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <table class="table table-bordered">
            <tr>
                <td>
                    @Html.LabelFor(model => model.Sname, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Sname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Sname, "", new { @class = "text-danger" })
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.Email, new { type = "email", htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Country, countries, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })

                </td>
                <td>
                    @Html.RadioButtonFor(model => model.Gender, "M", new { Checked = "true", htmlAttributes = new { @class = "form-control" } }) <b>Male</b>
                    @Html.RadioButtonFor(model => model.Gender, "F", new { htmlAttributes = new { @class = "form-control" } }) <b>Female</b>
                </td>
            </tr>



        </table>


        <div class="form-group mt-2">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@if (IsPost) {
    <table class="table table-bordered">
        <tr>
            <td>UserName: </td>
            <td>@Model.Sid </td>
        </tr>
        <tr>
            <td>Password: </td>
            <td>@Model.Password </td>
        </tr>
    </table>
}

MusicLibraryWebApp/Views/Singer/login.cshtml
@model MusicLibraryWebApp.Models.Singer

@{
    ViewBag.Title = "login";
}


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ActionLink("Singup", "SingUpSinger", "Singer")

    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.LabelFor(model => model.Sid, htmlAttributes: new { @class = "control-label col-md-2" })
                </th>
                <td>
                    @Html.EditorFor(model => model.Sid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sid, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                </th>
                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="LOGIN" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MusicLibraryWebApp/Views/Song/AddSong.cshtml
@model MusicLibraryWebApp.Models.Song

@{
    ViewBag.Title = "AddSong";
}

<b>Singer:</b> @Session["Sid"]
<b>Name:</b> @Session["Sname"]
<br />

<b>Album No: </b> @Request.QueryString["ano"]
<b>Album: </b> @Request.QueryString["title"]
<br />

<h2>Add Song</h2>

@using (Html.BeginForm("AddSong", "Song", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Ano)
        <div class="form-group">
            @Html.LabelFor(model => model.Sno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Mp3File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Mp3File, new { type = "File", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mp3File, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MusicLibraryWebApp/Views/Song/ViewSongs.cshtml
@model List<MusicLibraryWebApp.Models.Song>
@{
   ViewBag.Title = "ViewSongs";
}
<hr />
<h2>View Songs</h2>

<b>Singer:</b> @Session["Sid"]
<b>Name:</b> @Session["Sname"]
<br />

<b>Album No: </b> @Request.QueryString["ano"]
<b>Album: </b> @Request.QueryString["title"]
<br />

@Html.ActionLink("Add New Song", "AddSong", new {sid = Session["Sid"], 
    ano = Request.QueryString["ano"], 
    title = Request.QueryString["title"] })

<h2>All Songs</h2>
<table>
    <tr>
        <th>Sno</th>
        <th>Title</th>
        <th>File</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model) {
        <tr>
            <td>@item.Sno</td>
            <td>@item.Stitle</td>
            <td><embed src="@item.FilePath"  /></td>
            <td>@Html.ActionLink("Download", "DownloadSong", new {filePath = item.FilePath })</td>
        </tr>
    }
</table>